### ISSUE TITLE
Get into brew

### ISSUE THREAD

**Issue by fulldecent** [gburca/rofs-filtered#1]
This is a great filesystem! And I love to use it in tandem with encfs. Would be nice if this were available in Homebrew

**Comment by gburca** [comment]
I don't have an OS X device at this time, but patches are welcomed.

**Comment by fulldecent** [comment]
Here is progress so far

https://github.com/Homebrew/homebrew/pull/37926

There is advice here for anyone trying to build rofs-filtered on Mac

**Comment by fulldecent** [comment]
@gburca Could you please bump the version and make another tag and release. This will help make the packing easier for homebrew.

**Comment by fulldecent** [comment]
Bump

**Comment by gburca** [comment]
Version 1.5 tagged and released.

**Comment by fulldecent** [comment]
Thank you, updated link: https://github.com/Homebrew/homebrew/pull/38436

**Comment by fulldecent** [comment]
Brew formula passed validation, ready to merge soon

**Comment by fulldecent** [comment]
This is fixed with https://github.com/Homebrew/homebrew/commit/c947546ee039a9bfc6927c1255a6db5dde053855
