### ISSUE TITLE
Potential performance improvements.

### ISSUE THREAD

**Issue by layus** [gburca/rofs-filtered#14]
The current implementation builds separate regexes from each line in the file, then `shouldFilter` tries each one in order to discover a match.
This means the regexes are OR'ed, and we could build one big regex from all the fragments/lines.
Matching line A or line B or line C is exactly the same as matching (A)|(B)|(C).

Sadly, I have found no library to compose regexes, so it seems the way to go would be to build the full regex in a buffer before passing it to the regex engine.

Using one unified regex brings performance improvements on large directories, or when you have many regexes. Which is exactly my case.

---

In my use case, I have a directory with ten thousand of entries, and I want to allow access to only one thousand of these. So my config file looks like

```
\/$
\/.$
\/..$
^\/elem1(\/|$)
^\/elem2(\/|$)
...
^\/elem1000(\/|$)
```

I have tried building one big regex using the method described above, and it brings perceptible performance improvements. The drawback is that I had to increase the buffer size as the regex is one very long line. The default is 1024 chars and definitely not enough. I bumped it to 1024*1024.

Does anyone know of a library that allows to build regexes dynamically from other regexes ?

Regards,
-- Layus.

**Comment by gburca** [comment]
If your real config file is indeed similar to the example above, you should be able to accomplish your goal by tweaking the RE. The expressions are interpreted as having POSIX Extended Regular Expression syntax, which means you could use:

    ^\/elem[[:digit:]]{1,4}(\/|$)

or something similar to reduce the number of regex's in the config file. See `regex(7)`.

Bumping the buffer works until the next person comes along and needs `1024*1024+1`. A more flexible approach would be to dynamically increase the buffer to accommodate long REs.

Alternatively, instead of building regexes dynamically from other regexes, we could read the whole config file into an array of strings, combine the strings into the `(A)|(B)|(C)` form, and feed that single expression to regcomp.

**Comment by layus** [comment]
> If your real config file is indeed similar to the example above, you should be able to accomplish your goal by tweaking the RE. The expressions are interpreted as having POSIX Extended Regular Expression syntax, which means you could use:
> ```
> ^\/elem[[:digit:]]{1,4}(\/|$)
> ```
> or something similar to reduce the number of regex's in the config file. See regex(7).

Hmm, of course, that's what you get for giving too simple examples. My real config looks like
```
\/$
\/\.$
\/\.\.$
\/a0z98nhnfcgwflh59v3q4bpirvkfvl63-perl-XML-NamespaceSupport-1.11(\/|$)
\/013j77kmhc8mlivxa4ycnhz13i8z3l71-perl-XML-SAX-0.96(\/|$)
\/dad9vxniabwzidvvxfsfj6vb0xncsbbb-glibc-2.23(\/|$)
\/whiq76s59lzgsgpvcqz90ssaki56jw9s-attr-2.4.47(\/|$)
\/qknazr69bnl0ljn9jfgz29w0a87xbg1q-acl-2.2.52(\/|$)
\/038z6c3idjsy5a4gkqb70s1vml7ydylw-coreutils-8.25(\/|$)
\/03chmcis3gs2sclia5jr8vbzcvllzybs-etc-fstab(\/|$)
\/b4xk5zs6w92xnzg851idlh2380401id1-bash-4.3-p42(\/|$)
\/03w7k1j2xz5agp6yzmq4r6yhb9xmh3w4-unit-script(\/|$)
\/8b958w6vdf80c7v9hsxs6wmfacj5xaqq-libXdmcp-1.1.2(\/|$)
... and so on ...
```

> Bumping the buffer works until the next person comes along and needs 1024*1024+1. A more flexible approach would be to dynamically increase the buffer to accommodate long REs.

Indeed, that's never been my intention in the long term.

> Alternatively, instead of building regexes dynamically from other regexes, we could read the whole config file into an array of strings, combine the strings into the (A)|(B)|(C) form, and feed that single expression to regcomp.

Would you accept a PR for this ?

**Comment by gburca** [comment]
I'll accept patch if it's reasonable, but I might not be able to integrate it until after next week.

**Comment by fulldecent** [comment]
@layus perhaps use rofs-filtered BEFORE your encryption overlay system :-)

Here are some more notes about encryption + rofs, if anyone is interested:
https://github.com/vgough/encfs/issues/55

**Comment by layus** [comment]
@fulldecent This is not related at all to encryption. rofs has two roles
1) providing a read-only copy of a file-system (core feature)
2) providing a subset view of a file system (via a config file, and regexes)

I just want to make option 2 faster.

**Comment by fulldecent** [comment]
@layus Cool. Hmm... I was just very surprised by your specific regex config :-)

**Comment by layus** [comment]
The very specific regex config provides a view on the nix store. See nixos.org for more info.

**Comment by yunesj** [comment]
Indeed, rofs-filtered appears to be the bottleneck in my backup method.

@layus, thanks for the contribution! @gburca, what do you think of the pull request?

**Comment by gburca** [comment]
I just added some comments to the patch. I'll merge it in once they're addressed and the patch is rebased.
