### ISSUE TITLE
Fix Homebrew installation on macOS [$250 BOUNTY]

### ISSUE THREAD

**Issue by fulldecent** [gburca/rofs-filtered#18]
This is broken in macOS Sierra 10.12.1.

**Comment by fulldecent** [comment]
This problem is related to libfuse / configure.ac

A simple solution may be to rewrite the config system in CMake. Here is the relevant code that works in the encfs project. https://github.com/vgough/encfs/blob/master/cmake/FindFUSE.cmake

**Comment by fulldecent** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=40027989)](https://www.bountysource.com/issues/40027989-fix-homebrew-installation-on-macos?utm_source=40027989&utm_medium=shield&utm_campaign=ISSUE_BADGE)

Bounty added. I need this fixed.

Bounty requirements:

 * Bounty payment is $250.
 * Your pull request must solve the problem and be accepted into this project.
 * It must be accepted into Homebrew or Homebrew cask (it is already in there, so this update should be simple).
 * Your contribution must not break the build on Linux.
 * You must prove that it works by including a working `.travis.yml` that builds and tests for Mac and Linux. See my other pull request, this is basically already done.
 * This bounty offer expires in three months (on March 12, 2017).

**Comment by honggoff** [comment]
See https://github.com/honggoff/rofs-filtered/tree/use_cmake for my work in progress. So far it is only tested on Linux.

I am not familiar with homebrew but I will look into that now, to confirm this approach actually fixes the issue.

**Comment by honggoff** [comment]
I have it building using cmake in homebrew under 10.11.6. Unfortunately I do not have access to a machine with 10.12 at the moment, so I cannot reproduce the problem or check if it is fixed.

Could you try installing on your machine using the following command and report back the output? If it works I will adapt the travis configuration and create the pull request.

`brew install https://github.com/honggoff/homebrew-fuse/raw/rofs-cmake/Formula/rofs-filtered.rb`

**Comment by fulldecent** [comment]
@honggoff Thank you, I have used the

    brew install https://github.com/honggoff/homebrew-fuse/raw/rofs-cmake/Formula/rofs-filtered.rb

command and confirm it builds and works on macOS 10.12.1 (16B2555).

Great work!

**Comment by honggoff** [comment]
Thank you for paying out the bounty. I just followed up on the pull request in homebrew-fuse, for some reason there has not been any response from the maintainers.

**Comment by fulldecent** [comment]
Do you have a link to the upstream PR?

**Comment by fulldecent** [comment]
Thanks for your help. Maybe we can all make a quick comment there so they will accept it.

**Comment by fulldecent** [comment]
Ah here it is https://github.com/Homebrew/homebrew-fuse/pull/94#issuecomment-272199886
