### ISSUE TITLE
Can't open default config file

### ISSUE THREAD

**Issue by yunesj** [gburca/rofs-filtered#23]
rofs-filtered /Volumes/Filtered/ -o source=/
    rofs-filtered 1.7: Starting up. Using source: / and config: "/usr/local/etc"/rofs-filtered.rc
    Failed to open config file: "/usr/local/etc"/rofs-filtered.rc

It works fine if I specify the same config file explicitly.

    rofs-filtered /Volumes/Filtered/ -o source=/ -o config=/usr/local/etc/rofs-filtered.rc

This is using a `rofs-filtered: stable 1.7 (bottled)` installed via brew.

**Comment by gburca** [comment]
How is the config file passed in in the first instance? It looks wrong. It should not have those double quotes. I suspect there's something wrong with the brew scripts, which are not part of this (rofs-filtered) project.

**Comment by gburca** [comment]
Can you un-install the brew version and build + install from source to see if that works?

**Comment by yunesj** [comment]
I got the same error when building from source. It seemed to work, however, if I replaced the following line in `config.h.in`:

    #define SYSCONF_DIR "@CMAKE_INSTALL_FULL_SYSCONFDIR@"

with

    #define SYSCONF_DIR @CMAKE_INSTALL_FULL_SYSCONFDIR@

so that the resulting `config.h` instead includes

    #define SYSCONF_DIR /usr/local/etc

Thanks!
